releaseToProd check img

diff --git a/.github/workflows/releaseToProd.yml b/.github/workflows/releaseToProd.yml
--- a/.github/workflows/releaseToProd.yml
+++ b/.github/workflows/releaseToProd.yml
@@ -32,17 +32,25 @@ jobs:
 
       - name: Check if image with tag exists
         run: |
+          echo '${{secrets.YC_SA_JSON}}' > key.json
+          yc config set service-account-key key.json
+          yc config set cloud-id ${{secrets.YC_CLOUD_ID}}
+          yc config set folder-id ${{secrets.YC_FOLDER_ID}}
+
+          TAG="${{ github.event.inputs.release_version }}_latest"
+
           EXISTS=$(yc container image list \
+            --registry-id ${{ secrets.CR_ID }} \
             --repository-name "app" \
-            --format json | jq -r '.[].tags[]' | grep -Fx "${{ env.IMAGE_TAG }}" || true)
+            --format json | jq -r '.[].tags[]' | grep -Fx "$TAG" || true)
 
           if [ -z "$EXISTS" ]; then
-            echo "::error::Image ${{ env.IMAGE }} does not exist in Container Registry"
+            echo "::error::Image cr.yandex/${{ secrets.CR_ID }}/app:$TAG does not exist in Container Registry"
             exit 1
           else
-            echo "Image ${{ env.IMAGE }} exists"
+            echo "Image cr.yandex/${{ secrets.CR_ID }}/app:$TAG exists"
           fi
-
+          
       - name: CleanUp
         if: always()
         run: rm -f key.json
